// No daemon-internal imports — this module breaks the session-lifecycle ↔ bridge-dispatch cycle.
export const BRIDGE_TOOLS = [
  { name: 'reply', description: 'Reply in chat. Pass chat_id from the inbound message.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, text: { type: 'string' }, reply_to: { type: 'string', description: 'Message ID to thread under.' }, files: { type: 'array', items: { type: 'string' }, description: 'Absolute file paths to attach.' } }, required: ['chat_id', 'text'] } },
  { name: 'react', description: 'Add an emoji reaction to a message.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, message_id: { type: 'string' }, emoji: { type: 'string' } }, required: ['chat_id', 'message_id', 'emoji'] } },
  { name: 'edit_message', description: 'Edit a message the bot previously sent.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, message_id: { type: 'string' }, text: { type: 'string' } }, required: ['chat_id', 'message_id', 'text'] } },
  { name: 'delete_message', description: 'Delete a message. Bot can delete its own messages; in DMs the bot can also delete user messages.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, message_id: { type: 'string' } }, required: ['chat_id', 'message_id'] } },
  { name: 'download_attachment', description: 'Download attachments from a message.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, message_id: { type: 'string' } }, required: ['chat_id', 'message_id'] } },
  { name: 'create_thread', description: 'Create a thread in a channel.', inputSchema: { type: 'object', properties: { chat_id: { type: 'string' }, message_id: { type: 'string' }, name: { type: 'string' }, text: { type: 'string' }, auto_archive_minutes: { type: 'number' }, files: { type: 'array', items: { type: 'string' } } }, required: ['chat_id', 'name'] } },
  { name: 'fetch_messages', description: 'Fetch recent messages from a channel.', inputSchema: { type: 'object', properties: { channel: { type: 'string' }, limit: { type: 'number' } }, required: ['channel'] } },
  { name: 'spawn_session', description: 'Spawn a new Claude session. Pass worktree with a repo directory name (e.g. "options_bot") to spawn in an isolated git worktree. Set headless=true to skip thread creation (worker reports back via send_to_thread).', inputSchema: { type: 'object', properties: { topic: { type: 'string' }, chat_id: { type: 'string' }, message_id: { type: 'string' }, worktree: { type: 'string', description: 'Git repo subdirectory to create a worktree from (e.g. "options_bot", "anytester"). Session gets an isolated copy.' }, model: { type: 'string', description: 'Model ID for this spawn (overrides HYDRA_MODEL).' }, phase_budget: { type: 'string', description: 'Max session lifetime, e.g. "90s", "20m", "1h". At the deadline the session is told to checkpoint; 5 minutes later it is reaped.' }, headless: { type: 'boolean', description: 'Skip Discord thread creation. Worker communicates via send_to_thread to parent.' } }, required: ['topic'] } },
  { name: 'list_sessions', description: 'List all active sessions with name, context %, messages, and status.', inputSchema: { type: 'object', properties: {} } },
  { name: 'send_to_thread', description: 'Send a typed message to another session\'s thread. Every message must declare its type: progress (status update), question (needs input), or result (final deliverable).', inputSchema: { type: 'object', properties: { target: { type: 'string', description: 'Session name (e.g. "cedar"). Use list_sessions to discover names.' }, type: { type: 'string', enum: ['progress', 'question', 'result'], description: 'Message type: progress (status update), question (needs input from recipient), result (final deliverable).' }, text: { type: 'string' }, files: { type: 'array', items: { type: 'string' }, description: 'Absolute file paths to attach.' } }, required: ['target', 'type', 'text'] } },
  { name: 'peek_session', description: 'Read the last N lines of a child session\'s terminal output. Restricted to sessions you spawned (or all sessions for main). Non-intrusive — the target is not notified.', inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'Session name (tmux session name, e.g. "cedar").' }, lines: { type: 'number', description: 'Lines to capture (default 50, max 500).' } }, required: ['name'] } },
  { name: 'kill_session', description: 'Kill a session by ID or thread ID. Main session only.', inputSchema: { type: 'object', properties: { session_id: { type: 'string' }, thread_id: { type: 'string' } } } },
  { name: 'factory_build', description: 'Async daemon-enforced build→review cycle. Returns immediately with a ticket. Forks your session into a builder (inherits your context + can write code). When builder posts [done], daemon auto-starts adversarial review (builder defends its own code). After review, use factory_accept/factory_retry/factory_abandon. Multiple builds can run in parallel.', inputSchema: { type: 'object', properties: { spec: { type: 'string', description: 'What to build — precise spec with files, types, acceptance criteria.' }, difficulty: { type: 'string', enum: ['easy', 'medium', 'hard'], description: 'Task difficulty — selects builder/reviewer models. easy (default): sonnet builds, opus reviews. medium: opus builds, opus-4-8 reviews. hard: opus-5 builds, fable reviews.' }, builder_model: { type: 'string', description: 'Override builder model (e.g. "opus-5", "sonnet"). Takes priority over difficulty.' }, reviewer_model: { type: 'string', description: 'Override reviewer model. Takes priority over difficulty.' }, review_rounds: { type: 'number', description: 'Number of adversarial review rounds (default 3).' } }, required: ['spec'] } },
  { name: 'factory_retry', description: 'Send new instructions to an existing builder after review completes. Builder stays alive with full context and re-enters build→review. Only works in "awaiting_pm" phase.', inputSchema: { type: 'object', properties: { ticket: { type: 'string', description: 'Factory ticket ID (e.g. "fb-3-a1b2").' }, instructions: { type: 'string', description: 'What to fix — the builder already has full context from the prior build + review.' } }, required: ['ticket', 'instructions'] } },
  { name: 'factory_accept', description: 'Accept a completed build. Kills the builder. Only works in "awaiting_pm" phase.', inputSchema: { type: 'object', properties: { ticket: { type: 'string', description: 'Factory ticket ID.' } }, required: ['ticket'] } },
  { name: 'factory_abandon', description: 'Abandon a build. Kills the builder. Works in any phase.', inputSchema: { type: 'object', properties: { ticket: { type: 'string', description: 'Factory ticket ID.' } }, required: ['ticket'] } },
  { name: 'factory_status', description: 'Get status of your factory builds — ticket, phase, elapsed, builder name.', inputSchema: { type: 'object', properties: { ticket: { type: 'string', description: 'Specific ticket (optional — omit for all builds).' } } } },
  { name: 'set_description', description: 'Set a brief description for your session.', inputSchema: { type: 'object', properties: { session_id: { type: 'string' }, description: { type: 'string' } }, required: ['session_id', 'description'] } },
  { name: 'watch_pr', description: 'Watch a GitHub PR for new comments/reviews. The daemon polls every 3 min and delivers new feedback to your thread for triage. Omit pr_url to auto-detect from the current branch.', inputSchema: { type: 'object', properties: { pr_url: { type: 'string', description: 'Full GitHub PR URL. Omit to auto-detect from current branch via gh pr view.' }, chat_id: { type: 'string', description: 'Thread to deliver feedback to (defaults to your session thread)' } } } },
  { name: 'unwatch_pr', description: 'Stop watching a GitHub PR.', inputSchema: { type: 'object', properties: { pr_url: { type: 'string' } }, required: ['pr_url'] } },
  { name: 'list_watches', description: 'List all PRs being watched (your session or all).', inputSchema: { type: 'object', properties: { all: { type: 'boolean', description: 'Show all watches, not just yours' } } } },
  { name: 'decide', description: 'Make a protocol decision. The machine routes on value; your reasoning rides `because` and is narrated to the thread. For build reviews: value is "approve" or "request_changes". For post-pass lenses: value is "clean" or "findings".', inputSchema: { type: 'object', properties: { value: { type: 'string', description: 'The decision value — one of the options the protocol declares for this phase.' }, because: { type: 'string', description: 'Why. Posted to the thread as your review content.' } }, required: ['value', 'because'] } },
]

export const MAIN_ONLY_TOOLS = new Set(['spawn_session', 'kill_session'])

export function computeToolsForSession(sessionId: string, opts?: { allowMainTools?: boolean }): typeof BRIDGE_TOOLS {
  if (sessionId === 'main' || opts?.allowMainTools) return BRIDGE_TOOLS
  return BRIDGE_TOOLS.filter(t => !MAIN_ONLY_TOOLS.has(t.name))
}
