// Documentation inventory only. Reads source text; never imports daemon modules.
// Run: bun scripts/audit-claude-surface.ts [--check]
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, relative } from 'node:path'

const root = resolve(import.meta.dir, '..')
const read = (p: string) => readFileSync(resolve(root, p), 'utf8')
const files = [...new Bun.Glob('**/*.test.ts').scanSync({ cwd: root })]
  .filter(p => !p.includes('node_modules/') && !p.includes('.git/')).sort()
const link = (p: string, n?: number) => `[${p}${n ? ':' + n : ''}](../${p}${n ? '#L' + n : ''})`
const escape = (s: string) => s.replaceAll('|', '\\|').replaceAll('`', "'")
const matrix = read('docs/CLAUDE_FUNCTIONALITY_AUDIT.md')
const ids = new Set([...matrix.matchAll(/^\| ([A-Z]\d+) \|/gm)].map(m => m[1]))
const routeMap: Record<string, string> = {
  spawnCodexMatch:'L01', spawnCodexAliasMatch:'L01', spawnModelMatch:'L01', spawnModMatch:'L02', spawnMatch:'L01',
  spawnWtModelMatch:'L04', spawnWtCodexModelMatch:'L04', spawnWtMatch:'L04', killMatch:'L20', listMatch:'U11', templatesMatch:'U13',
  restartMatch:'U18', healthMatch:'U12', protocolsMatch:'U14', historyMatch:'U14', reconnectMatch:'U16', recoverMatch:'U17', commandsMatch:'U15',
  threadKillMatch:'L21', destroyMatch:'L22', respawnMatch:'L15', resumeMatch:'L13', usageMatch:'U10', peekMatch:'U09',
  forkCodexModelMatch:'L09', forkModelMatch:'L08', forkEphMatch:'L11', forkMatch:'L08', forksMatch:'L12', reviewMatch:'P01',
  cancelReviewMatch:'P07', buildV2Match:'P05', cancelBuildMatch:'P07', spikeV2Match:'P06', cancelSpikeMatch:'P07',
  watchMatch:'B19', unwatchMatch:'B19', watchesMatch:'B19', listenMatch:'U05', permReplyMatch:'U23', pauseMatch:'U06', keysMatch:'U07', permMatch:'U23',
}
const cliMap: Record<string,string> = {install:'B08',uninstall:'B08',up:'B09',down:'B09',restart:'B09',watchdog:'B10',preflight:'B10',spawn:'B01',list:'B02',status:'B02',kill:'B03',health:'B02','clear-key':'B04','check-key':'B04',factory:'B05',peek:'B06',attach:'B07'}
const toolNames = [...read('shared/tool-definitions.ts').matchAll(/^\s*\{ name: '([^']+)'/gm)].map(m => m[1])
const toolIds = ['reply','react','edit_message','delete_message','download_attachment','create_thread','fetch_messages','spawn_session','list_sessions','send_to_thread','peek_session','kill_session','factory_build','factory_retry','factory_accept','factory_abandon','factory_status','factory_review','set_description','watch_pr','unwatch_pr','list_watches','advance','extend_phase','factory_done']
function requireId(id: string | undefined, surface: string) {
  if (!id || !ids.has(id)) throw new Error(`Unmapped surface: ${surface}`)
  return id
}
const out = ['# Claude audit: test and surface catalogue', '',
  'Generated by `bun scripts/audit-claude-surface.ts`. Source-text inventory, not code coverage. No daemon or production state is loaded. See [the functionality matrix](CLAUDE_FUNCTIONALITY_AUDIT.md) for behavioral evidence and port decisions.', '',
  `Inventory: ${files.length} test files; ${toolNames.length} daemon tool definitions plus bridge-local get_session_info; ${ids.size} matrix rows. Test declarations below include describe groups, dynamic expressions, skipped tests and parameterized declarations as written; their count is not the number of executed tests.`, '',
  '## Explicit surfaces', '', '| Surface | Matrix | Source |', '|---|---|---|']
for (const name of toolNames) {
  const index = toolIds.indexOf(name)
  const id = index < 0 ? undefined : `M${String(index + 1).padStart(2,'0')}`
  out.push(`| MCP ${name} | ${requireId(id,name)} | ${link('shared/tool-definitions.ts')} |`)
}
out.push(`| MCP get_session_info (bridge local) | M26 | ${link('bridge.ts')} |`)
for (const [i, line] of read('daemon/router.ts').split('\n').entries()) {
  const m = line.match(/const (\w*Match)\s*=/)
  if (m) out.push(`| Router ${m[1]} | ${requireId(routeMap[m[1]],m[1])} | ${link('daemon/router.ts', i+1)} |`)
}
for (const [i,line] of read('cli/hydra.ts').split('\n').entries()) {
  const m = line.match(/case '([^']+)'/)
  if(m) out.push(`| CLI ${m[1]} | ${requireId(cliMap[m[1]],m[1])} | ${link('cli/hydra.ts',i+1)} |`)
}
out.push('', 'Non-match control flow is manually covered by U01–U04, U08, U19–U24 and B22: normal routing, dynamic template names, interrupt prefix, platform events, permission replies and Slack Home callbacks. This scanner is deliberately not presented as a parser for arbitrary router code.', '', '## Test declarations', '')
for (const file of files) {
  const name = file.split('/').at(-1)!.replace('.test.ts','')
  let disposition = 'Retain shared helper/behavior tests; matrix states the covered subset. Rewire dependencies only when the refactor crosses them.'
  if(name.startsWith('codex-')) disposition = 'Retain Codex-specific adapter regressions. These do not demonstrate native Claude behavior.'
  else if(name === 'pane-probe' || name === 'resume-health') disposition = 'Retain Claude-specific pane/process observation tests; share semantic health results, not terminal patterns.'
  else if(name === 'router-commands') disposition = 'REWRITE: copied regex tests are not actual router dispatch coverage; known stale listen/pause and build-wt cases.'
  else if(name === 'observability') disposition = 'Mixed: retain real log/autopsy tests; replace copied resumeCount logic with lifecycle execution.'
  else if(['topology-freshness','raw-send-ratchet','plugin-manifest'].includes(name)) disposition = 'Structural/source inventory checks, not behavior or live integration evidence.'
  else if(name.startsWith('protocol-')) disposition = 'Retain real DSL/runner semantics with fake timers/process boundaries; parameterize the runtime seam. No live Claude subprocess proof.'
  else if(name.startsWith('factory-')) disposition = 'Retain factory policy/orchestration. External lifecycle/git/gateway dependencies are mocked; real files alone do not prove git/process behavior.'
  else if(name === 'peek') disposition = 'CLI tmux behavior uses child_process mocks; isolate mock scope when extending integration coverage.'
  else if(['session-provider','session-health-provider','sessions','fork-strategy','auto-resume','recovery-dedup','recovery-selection','retirement-journal','bridge-transport','kill-destroy'].includes(name)) disposition = 'Candidate shared runtime/adapter contract seed. Preserve tested helper semantics; add real lifecycle/bridge coverage separately.'
  out.push(`### ${file}`, '', `${link(file)} — ${disposition}`, '')
  for(const [i,line] of read(file).split('\n').entries()) {
    if(/^\s*(?:describe|test|it)(?:\.(?:each|skip|todo|only))?\s*\(/.test(line)) {
      out.push(`- ${link(file,i+1)}: ${escape(line.trim())}`)
    }
  }
  out.push('')
}
out.push('## Production source index', '', 'Links for matrix implementation references. Presence in this index does not imply individual test coverage.', '')
const sources = [...new Bun.Glob('**/*.ts').scanSync({cwd:root})].filter(p => !p.includes('node_modules/') && !p.includes('/__tests__/') && !p.startsWith('__tests__/') && !p.startsWith('scripts/') && !p.includes('.git/')).sort()
for(const file of sources) out.push(`- ${link(file)}`)
const target = resolve(root,'docs/CLAUDE_TEST_CATALOGUE.md')
const result = out.join('\n') + '\n'
if(process.argv.includes('--check')) {
  if(readFileSync(target,'utf8') !== result) throw new Error('Catalogue stale: run bun scripts/audit-claude-surface.ts')
} else writeFileSync(target,result)
console.log(`${relative(root,target)}: ${files.length} suites, ${toolNames.length} daemon tools, ${ids.size} feature rows; mappings valid`)
